"""empty message

Revision ID: 302c5fa3934a
Revises: a92b9951a33e
Create Date: 2023-08-22 21:30:12.999162-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302c5fa3934a'
down_revision: Union[str, None] = 'a92b9951a33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
