"""empty message

Revision ID: 98924563dd28
Revises: 
Create Date: 2023-08-21 20:53:03.240001-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98924563dd28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.CheckConstraint('1 <= event_type and event_type <= 3', name='check_event_type_valid'),
    sa.ForeignKeyConstraint(['reported_by'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_reported_by'), 'event', ['reported_by'], unique=False)
    op.create_table('person_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('person', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Integer(), nullable=False),
    sa.CheckConstraint('1 <= relation_type and relation_type <= 2', name='check_relation_type_valid'),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.ForeignKeyConstraint(['person'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_event_event'), 'person_event', ['event'], unique=False)
    op.create_index(op.f('ix_person_event_person'), 'person_event', ['person'], unique=False)
    op.create_index(op.f('ix_person_event_relation_type'), 'person_event', ['relation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_event_relation_type'), table_name='person_event')
    op.drop_index(op.f('ix_person_event_person'), table_name='person_event')
    op.drop_index(op.f('ix_person_event_event'), table_name='person_event')
    op.drop_table('person_event')
    op.drop_index(op.f('ix_event_reported_by'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_table('event')
    op.drop_table('person')
    # ### end Alembic commands ###
